version: '3'

services:
  zookeerper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_CREATE_TOPICS= "myTopic:1:3,deleteTopic:1:3:compact"
    depends_on:
      - zookeerper
  my-blog-mongo:
    image: mongo:latest
    container_name: "my-blog-mongo"
    ports:
      - 27017:27017
  eureka-server:
    image: eurekaapp:1.0
    container_name: eureka-server
    ports:
      - 8761:8761
  api-gateway:
    image: gatewayapp:1.0
    container_name: api-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka-server
  blog-api-auth:
    image: blog-api-auth:1.0
    container_name: blog-api-auth
    ports:
      - 8083:8080
    links:
      - my-blog-mongo
    depends_on:
      - eureka-server
      - api-gateway
  blog-api-read:
    image: blog-api-auth:1.0
    container_name: blog-api-read
    ports:
      - 8082:8080
    links:
      - my-blog-mongo
    depends_on:
      - eureka-server
      - api-gateway
  blog-api-write:
    image: blog-api-auth:1.0
    container_name: blog-api-write
    ports:
      - 8081:8080
    links:
      - my-blog-mongo
    depends_on:
      - eureka-server
      - api-gateway